{
 "title": "Walrus Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_exporter_build_info{name='$name'},instance)"
    }
   },
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(node_exporter_build_info{env='$env'},name)"
    }
   },
   {
    "name": "env",
    "label": "surroundings",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Hardware Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Uptime CT",
     "type": "stat",
     "description": "Core node uptime",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(time() - node_boot_time_seconds)",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
      }
     ]
    },
    {
     "title": "System Health",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total[$interval])) * 100",
       "legendFormat": "CPU"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
       "legendFormat": "RAM"
      },
      {
       "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100",
       "legendFormat": "SWAP"
      },
      {
       "expr": "100 - (node_filesystem_free_bytes{device=\"/dev/sda2\"} *100 / node_filesystem_size_bytes{device=\"/dev/sda2\"})",
       "legendFormat": "Disk"
      },
      {
       "expr": "100 - (node_filesystem_free_bytes{device=\"/dev/sda1\"} *100 / node_filesystem_size_bytes{device=\"/dev/sda1\"})",
       "legendFormat": "Boot"
      }
     ]
    },
    {
     "title": "Currently open file descriptor",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filefd_allocated{instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Free space for each partition",
     "type": "table",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext4|xfs\"}"
      },
      {
       "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "node_memory_MemTotal_bytes{}", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "SWAP Total",
     "type": "stat",
     "description": "Total SWAP",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "node_memory_SwapTotal_bytes{}" }
     ]
    },
    {
     "title": "Avg. System Load",
     "type": "graph",
     "gridPos": { "h": 11, "w": 13, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "yaxes": [
      { "format": "%", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$node\"}*100",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{instance=~\"$node\"}*100",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{instance=~\"$node\"}*100",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "CPU usage, disk I/O operations per second take time（%）",
     "type": "graph",
     "description": "node_disk_io_time_seconds_total：\nThe number of milliseconds the disk spends on input/output operations. This value is the accumulated value.（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\nCalculate the rate per second: (last value - last previous value) / timestamp difference, that is, the percentage of time that the disk spends on I/O operations in 1 second.",
     "gridPos": { "h": 11, "w": 11, "x": 13, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1m]))",
       "legendFormat": "System"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1m]))",
       "legendFormat": "User"
      },
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}_% of I/O operations per second"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[1m]))",
       "legendFormat": "Iowait"
      }
     ]
    },
    {
     "title": "Disk read and write rate（IOPS）",
     "type": "graph",
     "description": "Reads completed: Reads per second per disk partition\n\nWrites completed: Number of writes per second per disk partition\n\nIO now Number of input/output requests being processed per disk partition per second",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "iops", "label": "Read (-) / write（+）I/O ops/sec" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}_read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}_write"
      }
     ]
    },
    {
     "title": "Disk read and write capacity",
     "type": "graph",
     "description": "Read bytes The number of bits read per second per disk partition\nWritten bytes The number of bits written per second per disk partition",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "Bps", "label": "Read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}_read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}_write"
      }
     ]
    },
    {
     "title": "Disk IO read and write time",
     "type": "graph",
     "description": "Read time ms Number of seconds per disk partition read operation\n\nWrite time ms Number of seconds spent per disk partition write operation\n\nIO time ms Number of seconds spent per disk partition input/output operation\n\n IO time weighted Weighted seconds spent per disk partition input/output operation",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "s", "label": "Read (-) / write (+) " }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}"
      },
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}_read"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}_write"
      },
      {
       "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}_weighted"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "bytes", "label": "Upload (-) / Download（+）" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*'}[5m])*8",
       "legendFormat": "{{device}}_in received"
      },
      {
       "expr": "-(irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*'}[5m])*8)",
       "legendFormat": "{{device}}_out sent"
      }
     ]
    },
    {
     "title": "TCP Connection situation",
     "type": "graph",
     "description": "CurrEstab - TCP connections with current state ESTABLISHED or CLOSE-WAIT\n\nActiveOpens - TCP average connections that have been converted from CLOSED state to SYN-SENT state (within 1 minute)\n\nPassiveOpens - Directly from LISTEN state The average number of TCP connections to SYN-RCVD state (within 1 minute)\n\nTCP_all oc - the number of TCP sockets allocated (established, applied to sk_buff)\n\nTCP_inuse - in use (listening The number of TCP sockets \n\nTCP_tw - the number of TCP connections waiting to be closed",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
       "legendFormat": "ESTABLISHED"
      },
      {
       "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'$node'}[1m])",
       "legendFormat": "ActiveOpens"
      },
      {
       "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'$node'}[1m])",
       "legendFormat": "PassiveOpens"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
       "legendFormat": "TCP_tw"
      },
      {
       "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
       "legendFormat": "TCP_alloc"
      },
      {
       "expr": "node_sockstat_TCP_inuse{instance=~'$node'}",
       "legendFormat": "TCP_inuse"
      }
     ]
    }
   ]
  },
  {
   "title": "Walrus Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Software Version",
     "type": "stat",
     "description": "Displays the currently running software version of the Walrus Storage Node.",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "walrus_build_info{group=\"WalrusNode\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Status Node",
     "type": "stat",
     "description": "Indicates if the Walrus Storage Node is active (1) or inactive (0).",
     "gridPos": { "h": 3, "w": 3, "x": 8, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "walrus_current_node_status{group=\"WalrusNode\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "Displays the uptime of the Walrus Storage Node.",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "uptime{group=\"WalrusNode\"}"
      }
     ]
    },
    {
     "title": "Current Epoch",
     "type": "stat",
     "description": "Displays the current epoch number for the Walrus Storage Node. ",
     "gridPos": { "h": 3, "w": 3, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "walrus_current_epoch{group=\"WalrusNode\"}"
      }
     ]
    },
    {
     "title": "Chain ID",
     "type": "stat",
     "description": "Displays the chain identifier of the Walrus network.",
     "gridPos": { "h": 3, "w": 4, "x": 17, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "uptime{group=\"WalrusNode\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Shards",
     "type": "stat",
     "description": "Displays the number of shards held by the Walrus Storage Node.",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "walrus_shards_owned{group=\"WalrusNode\"}"
      }
     ]
    },
    {
     "title": "Active Worker Count",
     "type": "stat",
     "description": "Tracks the number of workers handling checkpoint downloads.",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "checkpoint_downloader_num_workers{group=\"WalrusNode\"}"
      }
     ]
    },
    {
     "title": "Latest processed event",
     "type": "stat",
     "description": "Track the latest processed event (highest_finished)",
     "gridPos": { "h": 3, "w": 3, "x": 2, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "walrus_event_cursor_progress{state=\"highest_finished\", group=\"WalrusNode\"}"
      }
     ]
    },
    {
     "title": "Pending events",
     "type": "stat",
     "description": "Track pending events (pending) - should be near or come to 0 in a healthy system. If it continues to increase, then there is an issue.",
     "gridPos": { "h": 3, "w": 3, "x": 5, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "walrus_event_cursor_progress{state=\"pending\", group=\"WalrusNode\"}"
      }
     ]
    },
    {
     "title": "Total persisted events",
     "type": "stat",
     "description": " Track total persisted events (persisted)",
     "gridPos": { "h": 3, "w": 3, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "walrus_event_cursor_progress{state=\"persisted\", group=\"WalrusNode\"}"
      }
     ]
    },
    {
     "title": "Checkpoint Lag Monitoring",
     "type": "stat",
     "description": "Monitors how far behind the local node is compared to the full node.",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "checkpoint_downloader_checkpoint_lag{group=\"WalrusNode\"}"
      }
     ]
    },
    {
     "title": "Total Downloaded Checkpoints",
     "type": "stat",
     "description": " Track total downloaded checkpoints. ",
     "gridPos": { "h": 3, "w": 5, "x": 14, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "event_processor_total_downloaded_checkpoints{group=\"WalrusNode\"}"
      }
     ]
    },
    {
     "title": "Latest Downloaded Checkpoint",
     "type": "stat",
     "description": " Track latest downloaded checkpoint. ",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "event_processor_latest_downloaded_checkpoint{group=\"WalrusNode\"}"
      }
     ]
    },
    {
     "title": "GET Median HTTP Response Time",
     "type": "timeseries",
     "description": "Tracks the median duration of GET HTTP requests.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{method=\"GET\", group=\"WalrusNode\"}[$__rate_interval])) by (le, route, method))",
       "legendFormat": "{{method}} - {{route}}"
      }
     ]
    },
    {
     "title": "Median Time of Other HTTP Responses",
     "type": "timeseries",
     "description": "Tracks the median duration of Other HTTP requests.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{method!=\"GET\", group=\"WalrusNode\"}[$__rate_interval])) by (le, route, method))",
       "legendFormat": "{{method}} - {{route}}"
      }
     ]
    },
    {
     "title": "5 Most Requested GET Endpoints",
     "type": "barchart",
     "description": "Top 5 GET API endpoints by request count.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, sum(rate(http_request_duration_seconds_count{method=\"GET\"}[$__rate_interval])) by (route))",
       "legendFormat": "GET - {{route}}"
      }
     ]
    },
    {
     "title": "5 Most Requested Other HTTP Endpoints",
     "type": "barchart",
     "description": "Top 5 other API endpoints by request count.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, sum(rate(http_request_duration_seconds_count{method!=\"GET\"}[$__rate_interval])) by (route, method))",
       "legendFormat": " {{method}}- {{route}}"
      }
     ]
    },
    {
     "title": "Median HTTP Request Duration",
     "type": "timeseries",
     "description": "Identifies the median request duration for HTTP requests. There are 3 available queries.\nThe first query shows the median duration for all requests. The second  query shows the average  duration for all requests. The third query highlights the top 5 longest average request durations, helping to identify slowest API endpoints.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le, route, method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P95 HTTP Request Duration (95th Percentile)",
     "type": "timeseries",
     "description": "Identifies the 95th percentile (P95) request duration for HTTP requests, helping to identify slow-performing endpoints. There are two available queries.\nThe first query shows P95 durations for all requests, providing an overview of typical high-latency requests. The second query highlights the top 5 slowest P95 request durations, making it easier to detect the worst-performing routes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le, route, method))",
       "legendFormat": "{{method}} - {{route}}"
      }
     ]
    },
    {
     "title": "Node Status Over Time",
     "type": "timeseries",
     "description": "Tracks when the Walrus Storage Node goes offline and comes back online over time.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "walrus_current_node_status{group=\"WalrusNode\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Epoch Status Over Time",
     "type": "timeseries",
     "description": "Tracks the epoch status over time for the Walrus Storage Node. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "walrus_current_epoch_state{group=\"WalrusNode\"}",
       "legendFormat": "Epoch State - {{state}}"
      }
     ]
    },
    {
     "title": "Checkpoint Download Rate",
     "type": "barchart",
     "description": "This panel displays the rate of checkpoints downloaded per second for Walrus Storage Node. The values are dynamically adjusted using rate() to prevent amplitude spikes and provide a real-time view of sync performance. Sudden drops may indicate network or node issues.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(walrus_event_processor_latest_downloaded_checkpoint{group=\"WalrusNode\"}[$__rate_interval])",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "Checkpoint Download Rate",
     "type": "timeseries",
     "description": "This panel displays the rate of checkpoints downloaded per second over time for the Walrus Storage Node. The values are dynamically adjusted using rate() to prevent amplitude spikes and provide a real-time view of sync performance. Sudden drops may indicate network or node issues.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(walrus_event_processor_total_downloaded_checkpoints[$__rate_interval])",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "Total Checkpoints Downloaded (Last 5m)",
     "type": "barchart",
     "description": "It shows the total number of new checkpoints downloaded in the last 5 minutes for the Walrus Storage Node. A higher value means the system is processing checkpoints quickly.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(walrus_event_processor_total_downloaded_checkpoints[$__rate_interval])",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "Total Checkpoints Downloaded (Last 5m)",
     "type": "timeseries",
     "description": "It shows the total number of new checkpoints downloaded in the last 5 minutes for the Walrus Storage Node. A higher value means the system is processing checkpoints quickly.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(walrus_event_processor_total_downloaded_checkpoints[$__rate_interval])",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "Block Cache Hit Ratio (%)",
     "type": "timeseries",
     "description": "It shows the block cache hit ratio, which indicates how efficiently blocks are being read from cache instead of disk. A higher value (closer to 100%) means more reads are served from cache, improving performance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(block_cache_hit_count{group=\"WalrusNode\"}[$__rate_interval]) / (rate(block_cache_hit_count{group=\"WalrusNode\"}[$__rate_interval]) + rate(block_read_count{group=\"WalrusNode\"}[$__rate_interval])) * 100",
       "legendFormat": "{{cf_name}}"
      }
     ]
    },
    {
     "title": "Average Event Processing Time",
     "type": "timeseries",
     "description": "Displays the average processing time for each event type. The metric is calculated by dividing the total event processing duration by the total number of processed events over a 5-minute window. Higher values indicate slower processing, which may signal performance bottlenecks or system congestion.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(walrus_event_process_duration_seconds_sum{group=\"WalrusNode\"}[$__rate_interval])) by (event_type) \r\n/ \r\nsum(rate(walrus_event_process_duration_seconds_count{group=\"WalrusNode\"}[$__rate_interval])) by (event_type)",
       "legendFormat": "{{event_type}}"
      }
     ]
    },
    {
     "title": "Pending events",
     "type": "timeseries",
     "description": "It shows pending events over time - helps identify potential bottlenecks or issues locally or with the network.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "walrus_event_cursor_progress{state=\"pending\", group=\"WalrusNode\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Persisted vs. Processed Events",
     "type": "timeseries",
     "description": "It shows persisted vs. processed events over time - helps identify potential issues with processing or persisting events over time. Correlated to pending events.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "walrus_event_cursor_progress{state=\"persisted\", group=\"WalrusNode\"}",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "walrus_event_cursor_progress{state=\"highest_finished\", group=\"WalrusNode\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Walrus Publisher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Software Version",
     "type": "stat",
     "description": "Displays the currently running software version of the Walrus Publisher component.",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "walrus_build_info{group=\"WalrusPublisher\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Median Span Processing Time Publisher",
     "type": "timeseries",
     "description": "It shows the median time taken to process spans for each method and span name in the Walrus Publisher component. This helps identify slow spans and potential performance bottlenecks.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(tracing_span_latencies_bucket{group=\"WalrusPublisher\"}[$__rate_interval])) by (le, span_name, method))",
       "legendFormat": "{{method}} - {{span_name}}"
      }
     ]
    },
    {
     "title": "P95 Span Processing Time Publisher",
     "type": "timeseries",
     "description": "It shows the 95th percentile (P95) span processing time, showing the latency below which 95% of spans complete. \nThis helps identify high-latency spans and performance bottlenecks in distributed tracing, highlighting the slowest 5% of span executions.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, span_name) (rate(tracing_span_latencies_bucket{group=\"WalrusPublisher\"}[$__rate_interval])))",
       "legendFormat": "{{method}} - {{span_name}}"
      }
     ]
    },
    {
     "title": "GET Median HTTP Response Time",
     "type": "timeseries",
     "description": "Tracks how long GET HTTP requests take at the median for the Walrus Publisher component.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{method=\"GET\", group=\"WalrusPublisher\"}[$__rate_interval])) by (le, route))",
       "legendFormat": "{{group}}-{{route}}"
      }
     ]
    },
    {
     "title": "Other Median HTTP Response Time",
     "type": "timeseries",
     "description": "Tracks how long other HTTP requests take at the median for the Walrus Publisher component.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{method!=\"GET\", group=\"WalrusPublisher\"}[$__rate_interval])) by (le, route))",
       "legendFormat": "{{method}} - {{route}}"
      }
     ]
    },
    {
     "title": "Median Span Latency Publisher",
     "type": "timeseries",
     "description": "It tracks the median latency per span, , representing the time taken for a span to complete.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (span_name, le) (rate(tracing_span_latencies_bucket{group=\"WalrusPublisher\"}[$__rate_interval])))",
       "legendFormat": "{{span_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Walrus Aggregator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Software Version",
     "type": "stat",
     "description": "Displays the currently running software version of the Walrus Aggregator component.",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "walrus_build_info{group=\"WalrusAggregator\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GET Median HTTP Response Time",
     "type": "timeseries",
     "description": "Tracks how long GET HTTP requests take at the median for the Walrus Aggregator component.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (route, le) (rate(http_request_duration_seconds_bucket{method=\"GET\", group=\"WalrusAggregator\"}[$__rate_interval])))",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Other Median HTTP Response Time",
     "type": "timeseries",
     "description": "Tracks how long other HTTP requests take at the median for the Walrus Aggregator component.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (route, le) (rate(http_request_duration_seconds_bucket{method!=\"GET\", group=\"WalrusAggregator\"}[$__rate_interval])))",
       "legendFormat": "{{method}} - {{route}}"
      }
     ]
    },
    {
     "title": "Median Span Latency Aggregator",
     "type": "timeseries",
     "description": "It tracks the median latency per span, , representing the time taken for a span to complete.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (span_name, le) (rate(tracing_span_latencies_bucket{group=\"WalrusAggregator\"}[$__rate_interval])))",
       "legendFormat": "{{span_name}}"
      }
     ]
    }
   ]
  }
 ]
}